apiVersion : apps/v1
kind: Deployment
metadata:
  name: testpass
spec:
  replicas: 3
  selector:
    matchLabels:
      app: testpass
  template:
    metadata:
      labels:
        app: testpass
    spec:
      containers:
        - name: testpass
          image: vmprojectthree.azurecr.io/testapp2
          ports:
          - containerPort: 8000
