apiVersion : apps/v1
kind: Deployment
metadata:
  name: helloapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: helloapp
  template:
    metadata:
      labels:
        app: helloapp
    spec:
      containers:
        - name: helloapp
          image: vmprojectone.azurecr.io/testapp2
          ports:
          - containerPort: 8000
